#!/bin/bash

# SPDX-License-Identifier: GPL-2.0+

# Copyright © 2022-2026 Collabora Ltd
# Copyright © 2022-2026 Valve Corporation

LIBDIR=$(dirname "$0")

set -eu
. ${LIBDIR:-.}/holo-reset.sh
shopt -s extglob

set +e

declare -i RESET_OS="0"
declare -i RESET_USER="0"
declare -i RESET_ARGUMENT_USED="0"

declare -i UPDATE_PERFORMED="0"

declare -r RAUC_ROOTFS_INDEX=/var/lib/steamos-atomupd/rootfs.caibx
declare -r PARTSET_LINKDIR=/dev/disk/by-partsets

parse_args ()
{
    for arg in "$@"
    do
        case $arg in
            --reset-os)
                RESET_OS="1"
                RESET_ARGUMENT_USED="1"
               ;;
            --reset-user-data)
                RESET_USER="1"
                RESET_ARGUMENT_USED="1"
                ;;
            --reset-all)
                RESET_OS="1"
                RESET_USER="1"
                RESET_ARGUMENT_USED="1"
                ;;
        esac
    done

    # If no --reset argument was used, reset everything
    if [ $RESET_ARGUMENT_USED -eq "0" ]; then
        RESET_OS="1"
        RESET_USER="1"
    fi
}

parse_args "$@"

# If RAUC_ROOTFS_INDEX is present we can check if the rootfs is vanilla:
os_is_unmodified ()
{
    if [ ! -f $RAUC_ROOTFS_INDEX ]
    then
        log_msg "No index at $RAUC_ROOTFS_INDEX, cannot verify installed image"
        return 1;
    fi

    if ! type -t desync >/dev/null
    then
        log_msg "desync not available, cannot verify installed image"
        return 1
    fi

    log_msg "desync verifying $RAUC_ROOTFS_INDEX vs $PARTSET_LINKDIR/self/rootfs"
    if desync verify-index $RAUC_ROOTFS_INDEX $PARTSET_LINKDIR/self/rootfs
    then
        log_msg "Installed image is unmodified"
        return 0
    else
        log_msg "Installed image has been modified"
        return 1
    fi
}

generate_factory_reset_config ()
{
    local rv=0
    local cfg

    (cd $FACTORY_RESET_CONFIG_DIR && rm -vf * >&2)

    # suppress some annoying and unimportant warnings:
    if ! holo-factory-reset-config 2>&1
    then
         rv=1
    fi | (grep -vF 'mv: failed to preserve ownership'||true)

    cd $FACTORY_RESET_CONFIG_DIR
    while read cfg
    do
        case $cfg in
            efi-*) rm "$cfg"; ;;
            *) log_msg "Configuration for $cfg generated"; ;;
        esac
    done < <(ls -1)

    return $rv
}

update_os ()
{
    local -r flag=/run/.skip-os-reset

    if [ -f $flag ]
    then
        log_msg "Skipping actual atomic update, in test mode ($flag)"
        log_msg "# atomupd-manager update"
        for x in $(seq -f %02.0f 0 20 100);
        do
            sleep 1
            log_msg "New OS image: ${x}%"
        done
        holo-bootconf set-mode reboot-other
        return 0
    fi

    # Ensure we are on the stable branch, we always want to do a factory reset
    # to this. If we are already on this branch, this isn't going to hurt.
    if ! atomupd-manager switch-branch stable
    then
        log_msg "Failed to swtich to the stable branch"
        return 1
    fi

    # We will update to the latest stable release if one is available
    check=$(atomupd-manager check)
    if [[ $? != 0 ]]; then
        # If we fail to find the latest, check for the penultimate just in case.
        log_msg "Failed to check for update, fall back to penultimate update"
        check=$(atomupd-manager check --penultimate-update)
        if [[ $? != 0 ]]; then
            log_msg "Failed to check for penultimate update"
            return 1
        fi
    fi

    if [[ "$check" = "No update available" ]]; then
        # We need to install the current version, but only if the current OS is modified.
        if os_is_unmodified
        then
            log_msg "OS image up-to-date and unmodified - update not required"
            return 0
        else
            log_msg "Existing build modified, needs reinstall"
            if ! check=$(atomupd-manager list-builds --branch stable | tail -n 1)
            then
                log_msg "Failed to list latest stable release"
                return 1
            fi

        fi
    fi

    # Extract the buildid from the output
    id_line=${check#*ID: }
    buildid=${id_line/ */}

    atomupd-manager custom-update "$buildid" --verbose | while IFS= read -r line; do
        if [[ "$line" =~ ^[0-9]+\.[0-9]+% ]]; then
            log_msg "New OS image: $line"
        else
            log_msg "$line"
        fi
    done

    ret=${PIPESTATUS[0]}
    if [ $ret != 0 ]
    then
        return 1
    fi

    UPDATE_PERFORMED=1

    return 0
}

check_boot_status ()
{
    local -r current=$(holo-bootconf this-image)
    local -r selected=$(holo-bootconf selected-image)

    if [ $UPDATE_PERFORMED -eq 1 ]
    then
        if [ -z "${current:-}"  ] ||
           [ -z "${selected:-}" ] ||
           [ "$current" = "$selected" ]
        then
            log_msg "Bad boot config: current:${current:-?}, next:${selected:-?}"
            return 1
        else
            log_msg "Current image: ${current}; next boot: ${selected}"
            return 0
        fi
    else
        if [ -z "${current:-}"  ] ||
           [ -z "${selected:-}" ] ||
           [ "$current" != "$selected" ]
        then
            log_msg "Bad boot config: next:${selected:-?}, should be ${current:-?}"
            return 1
        else
            log_msg "Current image: ${current}; next boot: ${selected}"
            return 0
        fi
    fi
}

reset_os ()
{
    local report_success=${1:-yes}
    local cfg

    # Update the OS if it's required
    if ! update_os
    then
        set_session_status 500
        return 1
    fi

    if [ $UPDATE_PERFORMED = 0 ]
    then
        holo-bootconf set-mode reboot
        set_session_status 500
        return 0
    fi

    if check_boot_status
    then
        log_msg "Boot config OK, preparing to reset user data"
    else
        log_msg "Boot config not OK: Restoring boot to current image"
        holo-bootconf set-mode reboot
    fi

    log_msg "Factory reset ready"
    if [[ "${report_success}" == "yes" ]]; then
        set_session_status 200
    fi
    return 0
}

reset_user_data ()
{
    log_msg "Generating filesystem cleanup config in $FACTORY_RESET_CONFIG_DIR"
    if ! generate_factory_reset_config
    then
        log_msg "Failed to generate reset config"
        holo-bootconf set-mode reboot
        set_session_status 500
        return 0
    fi
    log_msg "Reset user data config ready"
    set_session_status 200
    return 0
}

log_msg "Factory-Reset $@ started at $(date +%Y-%m-%d\ %H:%M:%S\ %z)"

set_uuid
setup_session_dirs
set_session_type factory-reset
set_session_status 102

case $RESET_OS$RESET_USER in
    11)
        (close_stdio; register_session_pid;
         reset_os "dont_report_success"; reset_user_data) &
        ;;
    01)
        (close_stdio; register_session_pid; reset_user_data) &
        ;;
    10)
        (close_stdio; register_session_pid; reset_os ) &
        ;;
esac

[ -t 2 ] || disown

emit_json_response 102 "Factory reset started"
exit 0
