#!/bin/bash

# SPDX-License-Identifier: GPL-2.0+

# Copyright © 2022-2026 Collabora Ltd
# Copyright © 2022-2026 Valve Corporation

LIBDIR=$(dirname "$0")

set -eu
. ${LIBDIR:-.}/holo-reset.sh
shopt -s extglob
set +e

declare -r RAUC_ROOTFS_INDEX=/var/lib/steamos-atomupd/rootfs.caibx
declare -r PARTSET_LINKDIR=/dev/disk/by-partsets

# If RAUC_ROOTFS_INDEX is present we can check if the rootfs is vanilla:
os_is_unmodified ()
{    
    if [ ! -f $RAUC_ROOTFS_INDEX ]
    then
        log_msg "No index at $RAUC_ROOTFS_INDEX, cannot verify installed image"
        return 1;
    fi

    if ! type -t desync >/dev/null
    then
        log_msg "desync not available, cannot verify installed image"
        return 1
    fi
    
    log_msg "desync verifying $RAUC_ROOTFS_INDEX vs $PARTSET_LINKDIR/self/rootfs"
    if desync verify-index $RAUC_ROOTFS_INDEX $PARTSET_LINKDIR/self/rootfs
    then
        log_msg "Installed image is unmodified"
        return 0
    else
        log_msg "Installed image has been modified"
        return 1
    fi
}

check_os_status ()
{
    if os_is_unmodified
    then
        save_data update-needed txt 0
        save_data update-target txt ""
        set_session_status 200
	return
    fi

    log_msg "Reading update configuration"
    if ! output=$(atomupd-manager list-builds --branch stable | tail -n 1)
    then
        set_session_status 500
        log_msg "$output"
        return
    fi

    # Extract ID from atomupd-manager output
    buildid=$(sed -n 's/.*ID: \([0-9.]*\).*/\1/p' <<< "$output")
    if [ -n "$buildid" ]
    then
        save_data update-needed txt 1
        save_data update-target txt "${buildid:-}"
        set_session_status 200
        return
    fi

    set_session_status 500
    log_msg "Failed to determine suitable release"
}

emit_results ()
{
    local -r service=$(quote_escape $(basename "$0"))
    local -ir needed=$(get_data update-needed txt)
    local -r buildid=$(get_data update-target txt)

    emit_json_header
    cat - <<EOF
{"service": "$service",
 "version": "$VERSION",
 "status": 200,
 "message": "OS Status Check Complete",
 "uuid":"$UUID",
 "update":{"needed":$needed,"id":"$buildid"}}
EOF
}

results_if_complete ()
{
    local uuid=${1:-}
    local stype
    local state

    if ! uuid_ok "$uuid"
    then
        emit_json_response 400 "Malformed UUID '${uuid:-}'"
        exit 0
    fi

    set_uuid "$uuid"
    stype=$(get_session_type)

    if [ "${stype:-}" != "os-status" ]
    then
        emit_json_response 400 "Session $uuid is not an os-status check"
        exit 0
    fi

    state=$(get_session_status)

    case $state in
        200)
            emit_results
            ;;
        102)
            emit_json_response 102 "OS status check ongoing"
            ;;
        *)
            emit_json_response ${state:-400} "OS status check failed"
            ;;
    esac

    exit 0
}

# if asked for a specific UUID, we want the results (or status) of that
# os-status session:
declare sid arg
for arg in "$@"
do
    case $arg in
        uuid=*)
            sid=${arg#*=}
            results_if_complete "$sid"
            ;;
    esac
done

set_uuid
setup_session_dirs
set_session_type os-status
set_session_status 102

log_msg "OS-Status $@ started at $(date +%Y-%m-%d\ %H:%M:%S\ %z)"

(close_stdio; register_session_pid; check_os_status) &
disown

emit_json_response 102 "Checking OS Update Target"
exit 0
