#!/bin/bash

# SPDX-License-Identifier: GPL-2.0+

# Copyright © 2023 Collabora Ltd
# Copyright © 2023 Valve Corporation

LIBDIR=$(dirname "$0")

set -eu
. ${LIBDIR:-.}/steamos-reset.sh
shopt -s extglob
set +e

declare -r RAUC_ROOTFS_INDEX=/var/lib/steamos-atomupd/rootfs.caibx
declare -r PARTSET_LINKDIR=/dev/disk/by-partsets
declare ATOMUPD_QUERY_URL
declare ATOMUPD_IMAGE_URL
declare -r ATOMUPD_CONFIG=${1:-/etc/steamos-atomupd/client.conf}
declare -r ATOMUPD_MANIFEST=${2:-/etc/steamos-atomupd/manifest.json}
declare -A SELF
declare -A IMAGE
declare -r LIST_IMAGES=$(cat - <<EOF
<xsl:stylesheet version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform'>
  <xsl:output omit-xml-declaration="yes" indent="yes" encoding="utf-8"/>
  <xsl:strip-space elements="*"/>
  <xsl:template match="//table[@id='list']/tbody/tr/td[@class='link']/a">
    <xsl:value-of select="@title"/><xsl:text>&#10;</xsl:text>
  </xsl:template>
  <xsl:template match="text()"/>
</xsl:stylesheet>
EOF
);

declare FIND_MANIFEST=$(cat - <<EOF
<xsl:stylesheet version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform'>
  <xsl:output omit-xml-declaration="yes" indent="yes" encoding="utf-8"/>
  <xsl:strip-space elements="*"/>
  <xsl:template match="//table[@id='list']/tbody/tr/td[@class='link']/a[contains(@title,'manifest.json')]">
    <xsl:value-of select="@title"/><xsl:text>&#10;</xsl:text>
  </xsl:template>
  <xsl:template match="text()"/>
</xsl:stylesheet>
EOF
);

# If RAUC_ROOTFS_INDEX is present we can check if the rootfs is vanilla:
os_is_unmodified ()
{    
    if [ ! -f $RAUC_ROOTFS_INDEX ]
    then
        log_msg "No index at $RAUC_ROOTFS_INDEX, cannot verify installed image"
        return 1;
    fi

    if ! type -t desync >/dev/null
    then
        log_msg "desync not available, cannot verify installed image"
        return 1
    fi
    
    log_msg "desync verifying $RAUC_ROOTFS_INDEX vs $PARTSET_LINKDIR/self/rootfs"
    if desync verify-index $RAUC_ROOTFS_INDEX $PARTSET_LINKDIR/self/rootfs
    then
        log_msg "Installed image is unmodified"
        return 0
    else
        log_msg "Installed image has been moodified"
        return 1
    fi
}

# find an upgrade candidate from the atomupd server(s):
read_atomupd_config ()
{
    local key
    local op
    local val
    local section

    while read key op val op
    do
        case $key in
            \[*\])
                section=${key#\[}
                section=${section%\]}
                ;;
            *)
                if [ ${section:-none} = Server ];
                then
                    case $key in
                        QueryUrl) ATOMUPD_QUERY_URL="${val:-}"; ;;
                        ImagesUrl) ATOMUPD_IMAGE_URL="${val:-}"; ;;
                    esac
                fi
                ;;
        esac
    done < /etc/steamos-atomupd/client.conf

    log_msg "read /etc/steamos-atomupd/client.conf: "
    log_msg "${ATOMUPD_IMAGE_URL:-} ${ATOMUPD_QUERY_URL:-}"

    [ -n ${ATOMUPD_IMAGE_URL:-} ] && [ -n ${ATOMUPD_QUERY_URL:-} ]
}

read_atomupd_manifest ()
{
    local PRODUCT RELEASE VARIANT ARCH VER BUILD SKIP
    local -r JQ='"\(.product) \(.release) \(.variant) \(.arch) \(.version) \(.buildid) \(.skip? // false)"'
    read PRODUCT RELEASE VARIANT ARCH VER BUILD SKIP < <(jq -r "$JQ" "$1");

    IMAGE[product]=${PRODUCT:-steamos}
    IMAGE[release]=${RELEASE:-holo}
    IMAGE[variant]=${VARIANT:-steamdeck}
    IMAGE[arch]=${ARCH:-amd64}
    IMAGE[version]=${VER:-snapshot}
    IMAGE[build]=${BUILD:-19000101.1}
    IMAGE[skip]=${SKIP:-false}
}

read_current_manifest ()
{
    read_atomupd_manifest ${ATOMUPD_MANIFEST}
    SELF[product]=${IMAGE[product]}
    SELF[release]=${IMAGE[release]}
    SELF[variant]=${IMAGE[variant]}
    SELF[arch]=${IMAGE[arch]}
    SELF[version]=${IMAGE[version]}
    SELF[build]=${IMAGE[build]}
    # it doesn't matter if the current image is a 'skip' image
    # the OS reset will fix that anyway
}

resolve_fqdn ()
{
    local fqdn=${1:-unknown}
    local addr name

    while read addr name
    do
        case $addr in
            (+([0-9a-f:]))
              log_msg "$fqdn resolved to IPv6 $addr (${name:-})"
              return 0
              ;;
            (+([0-9].))
              log_msg "$fqdn resolved to IPv4 $addr (${name:-})"
              return 0
              ;;
        esac
    done < <(getent hosts "$fqdn" 2> /dev/null)

    log_msg "Network failure: Could not resolve server name $fqdn"
    return 1
}

network_ok ()
{
    local fqdn url

    for url in ${ATOMUPD_IMAGE_URL:-unknown} ${ATOMUPD_QUERY_URL:-unknown}
    do
        fqdn=${url#*//}
        fqdn=${fqdn%/*}
        if ! resolve_fqdn "$fqdn"
        then
            return 1
        fi
    done

    url="${ATOMUPD_IMAGE_URL:-}${SELF[variant]}"/

    if curl -s -I "$url"
    then
        return 0
    fi

    log_msg "Network failure: unsatisfactory response from ${url:-}"
    return 1
}

check_stable_update ()
{
    local variant path
    local -r JQ_VAR='\(.minor.candidates[0].image.variant)'
    local -r JQ_PATH='\(.minor.candidates[0].update_path)'

    log_msg "Calling steamos-atomupd-client to obtain update candidate"

    read variant path < \
         <(jq -r  "\"$JQ_VAR $JQ_PATH\"" <(steamos-atomupd-client --query-only))

    if [ "${variant:-null}" = null ]
    then
        log_msg "No pending updates found"
    else
        log_msg "Update is ${ATOMUPD_IMAGE_URL:-}${path:-} (${variant:-})"
    fi

    case ${variant:-none} in
        steamdeck)
            echo ${ATOMUPD_IMAGE_URL}${path:-}
            ;;
        *)
            return 1
            ;;
    esac
}

get_manifest_filename ()
{
    local manifest=
    local -r url_dir=${1}

    while read manifest
    do
        [ -n "$manifest" ] && break
    done < <(xsltproc --html <(echo "$FIND_MANIFEST") <(curl -s "$url_dir"))

    echo "$manifest"
}

find_reset_image ()
{
    read_current_manifest

    local -r base="${ATOMUPD_IMAGE_URL}${SELF[variant]}"
    local id stub manifest self_sig image_sig x

    if selected=$(check_stable_update)
    then
        save_data update-target txt "${selected:-}"
        set_session_status 200
        return 0
    fi

    if ! network_ok
    then
        log_msg "Update server not reachable"
        set_session_status 511
        return 0
    fi

    log_msg "Searching for 'steamdeck' image which is not ${SELF[build]}"
    
    while read id;
    do
        case $id in
            (+([0-9]).+([0-9]))
              # the metadata stub is no longer fixed "VARIANT-ID-snapshot"
              # so we have to go look and see what it is:
              stub="$base/$id/"
              manifest=$(get_manifest_filename "$stub")
              stub="$base/$id/${manifest%.manifest.json}"

              if read_atomupd_manifest <(curl -s "$base/$id/$manifest")
              then
                  log_msg "$id is a ${IMAGE[variant]} image"

                  # ignore 'skip' images
                  if [ "${IMAGE[skip]:-false}" != false ];
                  then
                      log_msg "$id is marked 'skip: ${IMAGE[skip]:-}'"
                      continue;
                  fi;

                  # only consider stable images
                  if [ "${IMAGE[variant]}" != steamdeck ]; then continue; fi

                  # if we're not on stable, just pick the newest stable image
                  if [ "${SELF[variant]}" != steamdeck ]
                  then
                      selected="${stub}.raucb"
                      break
                  # we're on stable, pick the newest that isn't us: 
                  elif [ "${SELF[build]}" != "${IMAGE[build]}" ]
                  then
                      selected="${stub}.raucb"
                      break
                  else
                      # for reasons (to do with btrfs & duplicate fs uuids)
                      # we cannot have two or more copies of an image installed
                      log_msg "${SELF[build]} already installed, skipping..."
                  fi
              fi
            ;;
        esac
    done < <(xsltproc --html <(echo "$LIST_IMAGES") <(curl -s "${base}/") | sort -rn)

    log_msg "Current image ${SELF[build]} (${SELF[variant]})"
    log_msg "Selecting ${IMAGE[build]} (${IMAGE[variant]})"

    save_data update-target txt "$selected"
    set_session_status 200
}

check_os_status ()
{
    if os_is_unmodified;
    then
        save_data update-needed txt 0
        save_data update-target txt ""
        set_session_status 200
    else
        log_msg "Reading update configuration"
        if ! read_atomupd_config
        then
            set_session_status 500
            log_msg "/etc/steamos-atomupd/client.conf invalid"
            log_msg "Query URL: ${ATOMUPD_QUERY_URL:-}"
            log_msg "Image URL: ${ATOMUPD_IMAGE_URL:-}"
            return
        else
            set_session_status 102
            save_data update-needed txt 1
            find_reset_image
        fi
    fi
}

emit_results ()
{
    local -r service=$(quote_escape $(basename "$0"))
    local -ir needed=$(get_data update-needed txt)
    local -r url=$(get_data update-target txt)

    emit_json_header
    cat - <<EOF
{"service": "$service",
 "version": "$VERSION",
 "status": 200,
 "message": "OS Status Check Complete",
 "uuid":"$UUID",
 "update":{"needed":$needed,"url":"$url"}}
EOF
}

results_if_complete ()
{
    local uuid=${1:-}
    local stype
    local state

    if ! uuid_ok "$uuid"
    then
        emit_json_response 400 "Malformed UUID '${uuid:-}'"
        exit 0
    fi

    set_uuid "$uuid"
    stype=$(get_session_type)

    if [ "${stype:-}" != "os-status" ]
    then
        emit_json_response 400 "Session $uuid is not an os-status check"
        exit 0
    fi

    state=$(get_session_status)

    case $state in
        200)
            emit_results
            ;;
        102)
            emit_json_response 102 "OS status check ongoing"
            ;;
        *)
            emit_json_response ${state:-400} "OS status check failed"
            ;;
    esac

    exit 0
}

# if asked for a specific UUID, we want the results (or status) of that
# os-status session:
declare sid arg
for arg in "$@"
do
    case $arg in
        uuid=*)
            sid=${arg#*=}
            results_if_complete "$sid"
            ;;
    esac
done

set_uuid
setup_session_dirs
set_session_type os-status
set_session_status 102

log_msg "OS-Status $@ started at $(date +%Y-%m-%d\ %H:%M:%S\ %z)"

(close_stdio; register_session_pid; check_os_status) &
disown

emit_json_response 102 "Checking OS Update Target"
exit 0
